-- ============================================================
-- JBOS PostgreSQL Schema (Neon)
-- Idempotent (CREATE … IF NOT EXISTS). Bootstrap-safe on every boot.
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name       text    NOT NULL,
  email           text    NOT NULL UNIQUE,
  password_hash   text    NOT NULL,
  role            text    NOT NULL DEFAULT 'sales_executive', -- super_admin | admin | sales_executive
  is_active       boolean NOT NULL DEFAULT true,
  last_login_at   timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(lower(email));

-- ============================================================
-- Company Settings (M3) — single-row table (id = 1 invariant)
-- ============================================================
CREATE TABLE IF NOT EXISTS company_settings (
  id                      smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  -- Business identity (replaces env fallbacks in template.service)
  company_name            text NOT NULL DEFAULT 'Aurum Atelier',
  company_tagline         text NOT NULL DEFAULT 'Fine Custom Jewellery · Est. 2008',
  company_address         text NOT NULL DEFAULT '14, Jewellers Row, Zaveri Bazaar<br>Mumbai — 400 002, Maharashtra, India',
  company_contact         text NOT NULL DEFAULT '+91 98200 XXXXX · atelier@aurum.in',
  company_web             text NOT NULL DEFAULT 'www.aurumatelier.com · @aurum_atelier',
  company_gstin           text NOT NULL DEFAULT 'GSTIN: 27AAXCA1234R1Z5',
  company_logo_url        text,
  -- Quotation defaults
  quotation_footer        text NOT NULL DEFAULT 'Crafted with Devotion',
  quotation_terms         text NOT NULL DEFAULT '',
  quotation_validity_days integer NOT NULL DEFAULT 30,
  whatsapp_default_message text NOT NULL DEFAULT '',
  -- Pricing defaults
  default_pricing_location text NOT NULL DEFAULT 'Mumbai',
  default_markup_pct       numeric(5,2) NOT NULL DEFAULT 18,
  -- Audit
  updated_by_user_id      bigint REFERENCES users(id) ON DELETE SET NULL,
  updated_at              timestamptz NOT NULL DEFAULT now(),
  created_at              timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- Master data (M3) — admin-editable dropdown catalogs
--   Same shape across all six types; columns are intentionally minimal.
--   `extra` jsonb lets a single CRUD layer carry per-type fields
--   (e.g. making preset's charge_type + charge_value).
-- ============================================================
CREATE TABLE IF NOT EXISTS master_product_categories (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label       text NOT NULL,
  sort_order  integer NOT NULL DEFAULT 100,
  is_active   boolean NOT NULL DEFAULT true,
  extra       jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_mpc_label ON master_product_categories(lower(label));

CREATE TABLE IF NOT EXISTS master_metal_types (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label       text NOT NULL,
  sort_order  integer NOT NULL DEFAULT 100,
  is_active   boolean NOT NULL DEFAULT true,
  extra       jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_mmt_label ON master_metal_types(lower(label));

CREATE TABLE IF NOT EXISTS master_purities (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label       text NOT NULL,
  sort_order  integer NOT NULL DEFAULT 100,
  is_active   boolean NOT NULL DEFAULT true,
  extra       jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_mpu_label ON master_purities(lower(label));

CREATE TABLE IF NOT EXISTS master_diamond_types (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label       text NOT NULL,
  sort_order  integer NOT NULL DEFAULT 100,
  is_active   boolean NOT NULL DEFAULT true,
  extra       jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_mdt_label ON master_diamond_types(lower(label));

CREATE TABLE IF NOT EXISTS master_cities (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label       text NOT NULL,
  sort_order  integer NOT NULL DEFAULT 100,
  is_active   boolean NOT NULL DEFAULT true,
  extra       jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_mc_label ON master_cities(lower(label));

-- Making presets carry charge_type + charge_value inside `extra`:
--   extra = { "charge_type": "per_gram" | "fixed" | "percentage", "charge_value": 1200 }
CREATE TABLE IF NOT EXISTS master_making_presets (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label       text NOT NULL,
  sort_order  integer NOT NULL DEFAULT 100,
  is_active   boolean NOT NULL DEFAULT true,
  extra       jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_mmp_label ON master_making_presets(lower(label));

-- ============================================================
-- Audit log (M2 foundation; extend in later milestones)
-- ============================================================
CREATE TABLE IF NOT EXISTS audit_events (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id   bigint REFERENCES users(id) ON DELETE SET NULL,
  actor_email     text,                          -- denormalised so log survives user delete
  action          text NOT NULL,                 -- e.g. 'auth.login', 'quotation.create', 'user.create'
  entity_type     text,                          -- 'quotation' | 'user' | 'auth' ...
  entity_id       text,                          -- string for portability across PK types
  metadata        jsonb NOT NULL DEFAULT '{}'::jsonb,
  ip              text,
  user_agent      text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_audit_actor   ON audit_events(actor_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_action  ON audit_events(action, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_entity  ON audit_events(entity_type, entity_id, created_at DESC);


CREATE TABLE IF NOT EXISTS quotations (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id            text    NOT NULL UNIQUE,
  status              text    NOT NULL DEFAULT 'draft',   -- draft | sent | accepted | expired

  -- Customer
  customer_name       text    NOT NULL,
  customer_mobile     text,
  customer_email      text,
  occasion            text,

  -- Product
  product_name        text,
  product_category    text,
  product_description text,
  product_image_path  text,

  -- Metal
  metal_type          text,
  metal_color         text,
  purity              text,
  gross_weight        double precision DEFAULT 0,
  net_weight          double precision DEFAULT 0,

  -- Diamond
  diamond_type        text,
  diamond_shape       text,
  diamond_carat       double precision DEFAULT 0,
  diamond_clarity     text,
  diamond_color       text,

  -- Gemstone
  gemstone            text,
  gemstone_carat      double precision DEFAULT 0,

  -- Certifications
  hallmark            text,
  certification       text,
  setting_style       text,

  -- Rates snapshot (frozen at creation)
  gold_rate_per_gram      double precision DEFAULT 0,
  diamond_rate_per_carat  double precision DEFAULT 0,
  gemstone_rate_per_carat double precision DEFAULT 0,

  -- Making
  making_charge_type      text DEFAULT 'per_gram',
  making_charge_value     double precision DEFAULT 0,

  -- Extras
  hallmark_charge         double precision DEFAULT 0,
  certification_charge    double precision DEFAULT 0,
  shipping_charge         double precision DEFAULT 0,

  -- Computed
  gold_cost           double precision DEFAULT 0,
  diamond_cost        double precision DEFAULT 0,
  gemstone_cost       double precision DEFAULT 0,
  making_charge       double precision DEFAULT 0,
  subtotal            double precision DEFAULT 0,
  gst_rate            double precision DEFAULT 0.03,
  gst_amount          double precision DEFAULT 0,
  final_price         double precision DEFAULT 0,

  -- Meta
  pricing_location    text,
  sales_executive     text,
  valid_till          date,
  notes               text,
  pdf_path            text,

  -- WhatsApp delivery
  whatsapp_status     text,
  whatsapp_message_id text,
  whatsapp_sent_at    timestamptz,
  whatsapp_error      text,

  -- Ownership (M2 — RBAC visibility scoping)
  owner_user_id       bigint REFERENCES users(id) ON DELETE SET NULL,

  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);
-- idx_quotations_owner is created in connection.js after the column migration
-- runs, so existing databases get the column added before the index references it.

CREATE INDEX IF NOT EXISTS idx_quotations_quote_id   ON quotations(quote_id);
CREATE INDEX IF NOT EXISTS idx_quotations_created_at ON quotations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_quotations_customer   ON quotations(customer_name);

-- ============================================================
-- Rate Master Tables
-- ============================================================

CREATE TABLE IF NOT EXISTS gold_rates (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location       text NOT NULL DEFAULT 'Mumbai',
  purity         text NOT NULL,
  rate_per_gram  double precision NOT NULL,
  source         text NOT NULL DEFAULT 'manual',
  is_override    boolean NOT NULL DEFAULT false,
  effective_date date NOT NULL DEFAULT current_date,
  updated_at     timestamptz NOT NULL DEFAULT now(),
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_gold_rates_loc_purity ON gold_rates(location, purity, updated_at DESC);

CREATE TABLE IF NOT EXISTS diamond_rates (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shape          text NOT NULL,
  clarity        text,
  color          text,
  rate_per_carat double precision NOT NULL,
  effective_date date NOT NULL DEFAULT current_date,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_diamond_rates_shape ON diamond_rates(shape, effective_date DESC);

CREATE TABLE IF NOT EXISTS gemstone_rates (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gemstone       text NOT NULL,
  grade          text,
  rate_per_carat double precision NOT NULL,
  effective_date date NOT NULL DEFAULT current_date,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_gemstone_rates_name ON gemstone_rates(gemstone, effective_date DESC);

CREATE TABLE IF NOT EXISTS making_charges (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category       text NOT NULL,
  charge_type    text NOT NULL,
  charge_value   double precision NOT NULL,
  effective_date date NOT NULL DEFAULT current_date,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_making_charges_cat ON making_charges(category, effective_date DESC);
