-- ============================================================
-- JBOS PostgreSQL Schema (Neon)
-- Idempotent (CREATE … IF NOT EXISTS). Bootstrap-safe on every boot.
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name       text    NOT NULL,
  email           text    NOT NULL UNIQUE,
  password_hash   text    NOT NULL,
  role            text    NOT NULL DEFAULT 'sales_executive', -- super_admin | admin | sales_executive
  is_active       boolean NOT NULL DEFAULT true,
  last_login_at   timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(lower(email));

-- ============================================================
-- Company Settings (M3) — single-row table (id = 1 invariant)
-- ============================================================
CREATE TABLE IF NOT EXISTS company_settings (
  id                      smallint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  -- Business identity (replaces env fallbacks in template.service)
  company_name            text NOT NULL DEFAULT 'Aurum Atelier',
  company_tagline         text NOT NULL DEFAULT 'Fine Custom Jewellery · Est. 2008',
  company_address         text NOT NULL DEFAULT '14, Jewellers Row, Zaveri Bazaar<br>Mumbai — 400 002, Maharashtra, India',
  company_contact         text NOT NULL DEFAULT '+91 98200 XXXXX · atelier@aurum.in',
  company_web             text NOT NULL DEFAULT 'www.aurumatelier.com · @aurum_atelier',
  company_gstin           text NOT NULL DEFAULT 'GSTIN: 27AAXCA1234R1Z5',
  company_logo_url        text,
  -- Quotation defaults
  quotation_footer        text NOT NULL DEFAULT 'Crafted with Devotion',
  quotation_terms         text NOT NULL DEFAULT '',
  quotation_validity_days integer NOT NULL DEFAULT 30,
  whatsapp_default_message text NOT NULL DEFAULT '',
  -- Pricing defaults
  default_pricing_location text NOT NULL DEFAULT 'Mumbai',
  default_markup_pct       numeric(5,2) NOT NULL DEFAULT 18,
  -- Audit
  updated_by_user_id      bigint REFERENCES users(id) ON DELETE SET NULL,
  updated_at              timestamptz NOT NULL DEFAULT now(),
  created_at              timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- Master data (M3) — admin-editable dropdown catalogs
--   Same shape across all six types; columns are intentionally minimal.
--   `extra` jsonb lets a single CRUD layer carry per-type fields
--   (e.g. making preset's charge_type + charge_value).
-- ============================================================
CREATE TABLE IF NOT EXISTS master_product_categories (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label       text NOT NULL,
  sort_order  integer NOT NULL DEFAULT 100,
  is_active   boolean NOT NULL DEFAULT true,
  extra       jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_mpc_label ON master_product_categories(lower(label));

CREATE TABLE IF NOT EXISTS master_metal_types (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label       text NOT NULL,
  sort_order  integer NOT NULL DEFAULT 100,
  is_active   boolean NOT NULL DEFAULT true,
  extra       jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_mmt_label ON master_metal_types(lower(label));

CREATE TABLE IF NOT EXISTS master_purities (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label       text NOT NULL,
  sort_order  integer NOT NULL DEFAULT 100,
  is_active   boolean NOT NULL DEFAULT true,
  extra       jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_mpu_label ON master_purities(lower(label));

CREATE TABLE IF NOT EXISTS master_diamond_types (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label       text NOT NULL,
  sort_order  integer NOT NULL DEFAULT 100,
  is_active   boolean NOT NULL DEFAULT true,
  extra       jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_mdt_label ON master_diamond_types(lower(label));

CREATE TABLE IF NOT EXISTS master_cities (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label       text NOT NULL,
  sort_order  integer NOT NULL DEFAULT 100,
  is_active   boolean NOT NULL DEFAULT true,
  extra       jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_mc_label ON master_cities(lower(label));

-- Making presets carry charge_type + charge_value inside `extra`:
--   extra = { "charge_type": "per_gram" | "fixed" | "percentage", "charge_value": 1200 }
CREATE TABLE IF NOT EXISTS master_making_presets (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label       text NOT NULL,
  sort_order  integer NOT NULL DEFAULT 100,
  is_active   boolean NOT NULL DEFAULT true,
  extra       jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_mmp_label ON master_making_presets(lower(label));

-- ============================================================
-- CRM Core (M4) — Lead management
-- ============================================================

-- Lead source + status catalogs (admin-editable later; seeded on boot).
CREATE TABLE IF NOT EXISTS lead_sources (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label       text NOT NULL,
  sort_order  integer NOT NULL DEFAULT 100,
  is_active   boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_lead_sources_label ON lead_sources(lower(label));

CREATE TABLE IF NOT EXISTS lead_statuses (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label       text NOT NULL,
  sort_order  integer NOT NULL DEFAULT 100,
  is_active   boolean NOT NULL DEFAULT true,
  is_terminal text,                              -- 'converted' | 'lost' | null
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_lead_statuses_label ON lead_statuses(lower(label));

CREATE TABLE IF NOT EXISTS leads (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_code              text NOT NULL UNIQUE,
  name                   text NOT NULL,
  mobile                 text NOT NULL,
  email                  text,
  occasion               text,
  budget                 numeric(12,2),
  notes                  text,
  source_id              bigint REFERENCES lead_sources(id) ON DELETE SET NULL,
  status_id              bigint REFERENCES lead_statuses(id) ON DELETE SET NULL,
  priority               text NOT NULL DEFAULT 'medium',   -- low | medium | high
  assigned_user_id       bigint REFERENCES users(id) ON DELETE SET NULL,
  created_by_user_id     bigint REFERENCES users(id) ON DELETE SET NULL,
  converted_customer_id  bigint,                            -- M5 customers (loose link)
  converted_quotation_id bigint,                            -- set when a quote is raised
  converted_at           timestamptz,                       -- when the lead became Converted
  next_followup_at       timestamptz,
  is_converted           boolean NOT NULL DEFAULT false,
  is_lost                boolean NOT NULL DEFAULT false,
  created_at             timestamptz NOT NULL DEFAULT now(),
  updated_at             timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_leads_mobile     ON leads(mobile);
CREATE INDEX IF NOT EXISTS idx_leads_assigned   ON leads(assigned_user_id);
CREATE INDEX IF NOT EXISTS idx_leads_status     ON leads(status_id);
CREATE INDEX IF NOT EXISTS idx_leads_source     ON leads(source_id);
CREATE INDEX IF NOT EXISTS idx_leads_followup   ON leads(next_followup_at);
CREATE INDEX IF NOT EXISTS idx_leads_created    ON leads(created_at DESC);

CREATE TABLE IF NOT EXISTS lead_followups (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_id            bigint NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  followup_date      timestamptz NOT NULL DEFAULT now(),
  notes              text NOT NULL,
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_lead_followups_lead ON lead_followups(lead_id, created_at DESC);

-- ============================================================
-- Advanced CRM (M5) — Customers, Timeline, Reminders
-- ============================================================
CREATE TABLE IF NOT EXISTS customers (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_code     text NOT NULL UNIQUE,
  name              text NOT NULL,
  mobile            text NOT NULL,
  email             text,
  address           text,
  birthday          date,
  anniversary       date,
  ring_size         text,
  preferred_metal   text,
  budget_range      text,
  notes             text,
  assigned_user_id  bigint REFERENCES users(id) ON DELETE SET NULL,
  source_lead_id    bigint REFERENCES leads(id) ON DELETE SET NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);
-- Mobile is the dedupe identity. Unique so conversion can't create twins.
CREATE UNIQUE INDEX IF NOT EXISTS uq_customers_mobile ON customers(mobile);
CREATE INDEX IF NOT EXISTS idx_customers_assigned ON customers(assigned_user_id);
CREATE INDEX IF NOT EXISTS idx_customers_code     ON customers(customer_code);

CREATE TABLE IF NOT EXISTS customer_events (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id    bigint NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  event_type     text NOT NULL,        -- lead_converted | quotation_sent | reminder_added | profile_updated | note | ...
  title          text NOT NULL,
  notes          text,
  actor_user_id  bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_customer_events_cust ON customer_events(customer_id, created_at DESC);

CREATE TABLE IF NOT EXISTS reminder_tasks (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id        bigint REFERENCES customers(id) ON DELETE CASCADE,
  lead_id            bigint REFERENCES leads(id) ON DELETE SET NULL,
  title              text NOT NULL,
  notes              text,
  due_at             timestamptz NOT NULL,
  status             text NOT NULL DEFAULT 'pending',  -- pending | done
  assigned_user_id   bigint REFERENCES users(id) ON DELETE SET NULL,
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  done_at            timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_reminders_due       ON reminder_tasks(due_at);
CREATE INDEX IF NOT EXISTS idx_reminders_assigned  ON reminder_tasks(assigned_user_id, status);

-- ============================================================
-- HRMS (M6) — Employees, Attendance, Leaves
-- ============================================================
CREATE TABLE IF NOT EXISTS employees (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_code       text NOT NULL UNIQUE,
  user_id             bigint UNIQUE REFERENCES users(id) ON DELETE SET NULL, -- one profile per user
  full_name           text NOT NULL,
  email               text,
  mobile              text,
  role                text,                  -- mirrors user role at create time
  department          text,
  designation         text,
  joining_date        date,
  birthday            date,
  reporting_manager_id bigint REFERENCES employees(id) ON DELETE SET NULL,
  employment_status   text NOT NULL DEFAULT 'active', -- active | on_leave | resigned | terminated
  emergency_contact   text,
  address             text,
  notes               text,
  is_active           boolean NOT NULL DEFAULT true,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_employees_user ON employees(user_id);

CREATE TABLE IF NOT EXISTS attendance (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id      bigint NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  attendance_date  date NOT NULL,
  status           text NOT NULL DEFAULT 'present',  -- present | half_day | absent | leave
  check_in_time    text,
  check_out_time   text,
  notes            text,
  marked_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);
-- One row per employee per day.
CREATE UNIQUE INDEX IF NOT EXISTS uq_attendance_emp_date ON attendance(employee_id, attendance_date);
CREATE INDEX IF NOT EXISTS idx_attendance_date ON attendance(attendance_date DESC);

CREATE TABLE IF NOT EXISTS leaves (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id       bigint NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  leave_type        text NOT NULL,                   -- casual | sick | emergency | paid | unpaid
  start_date        date NOT NULL,
  end_date          date NOT NULL,
  reason            text,
  status            text NOT NULL DEFAULT 'pending', -- pending | approved | rejected
  decided_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  decided_at        timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_leaves_employee ON leaves(employee_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_leaves_status   ON leaves(status);
CREATE INDEX IF NOT EXISTS idx_leaves_dates    ON leaves(start_date, end_date);

-- ============================================================
-- Advanced HRMS (M7)
-- ============================================================
CREATE TABLE IF NOT EXISTS shifts (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shift_name  text NOT NULL,
  start_time  text,
  end_time    text,
  weekly_off  text,                  -- e.g. 'Sunday'
  is_active   boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tasks (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title              text NOT NULL,
  description        text,
  assigned_to_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  assigned_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  due_date           date,
  priority           text NOT NULL DEFAULT 'medium',  -- low | medium | high | urgent
  linked_entity_type text,                            -- lead | customer | quotation
  linked_entity_id   text,
  status             text NOT NULL DEFAULT 'pending',  -- pending | in_progress | completed | cancelled
  completed_at       timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_tasks_assignee ON tasks(assigned_to_user_id, status);
CREATE INDEX IF NOT EXISTS idx_tasks_due      ON tasks(due_date);

CREATE TABLE IF NOT EXISTS incentives (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id         bigint NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  type                text NOT NULL DEFAULT 'fixed',   -- percentage | fixed | target_bonus
  percentage          numeric(6,2),
  fixed_amount        numeric(12,2),
  amount              numeric(12,2),                   -- resolved payout amount
  linked_quotation_id bigint,
  linked_customer_id  bigint,
  notes               text,
  status              text NOT NULL DEFAULT 'draft',   -- draft | approved | paid
  approved_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  approved_at         timestamptz,
  paid_at             timestamptz,
  created_by_user_id  bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_incentives_emp    ON incentives(employee_id, status);
CREATE INDEX IF NOT EXISTS idx_incentives_status ON incentives(status);

CREATE TABLE IF NOT EXISTS employee_compensation (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id        bigint NOT NULL UNIQUE REFERENCES employees(id) ON DELETE CASCADE,
  salary_type        text NOT NULL DEFAULT 'monthly',  -- monthly | daily | contract
  base_salary        numeric(12,2) DEFAULT 0,
  allowance          numeric(12,2) DEFAULT 0,
  deduction          numeric(12,2) DEFAULT 0,
  overtime_rate      numeric(12,2) DEFAULT 0,
  commission_eligible boolean NOT NULL DEFAULT false,
  notes              text,
  updated_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS employee_documents (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id      bigint NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  document_name    text NOT NULL,
  category         text NOT NULL DEFAULT 'Other',   -- Identity | Employment | Legal | Other
  upload_url       text NOT NULL,
  uploaded_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  is_active        boolean NOT NULL DEFAULT true,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_emp_docs ON employee_documents(employee_id, is_active);

-- ============================================================
-- HR calendar manual events (M7 fix pack)
--   Auto events (leaves, birthdays, anniversaries, approvals, followups,
--   task deadlines) are derived from existing tables at read time. This table
--   stores admin-created manual events (meetings, exhibitions, holidays, …).
-- ============================================================
CREATE TABLE IF NOT EXISTS calendar_events (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title              text NOT NULL,
  description        text,
  event_date         date NOT NULL,
  category           text NOT NULL DEFAULT 'general', -- meeting | exhibition | audit | holiday | promotion | training | general
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  is_active          boolean NOT NULL DEFAULT true,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_calendar_events_date ON calendar_events(event_date, is_active);
-- Reject duplicate active events with the same title on the same date (case-insensitive).
CREATE UNIQUE INDEX IF NOT EXISTS uq_calendar_events_title_date
  ON calendar_events(lower(title), event_date) WHERE is_active;

-- ============================================================
-- Audit log (M2 foundation; extend in later milestones)
-- ============================================================
CREATE TABLE IF NOT EXISTS audit_events (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_user_id   bigint REFERENCES users(id) ON DELETE SET NULL,
  actor_email     text,                          -- denormalised so log survives user delete
  action          text NOT NULL,                 -- e.g. 'auth.login', 'quotation.create', 'user.create'
  entity_type     text,                          -- 'quotation' | 'user' | 'auth' ...
  entity_id       text,                          -- string for portability across PK types
  metadata        jsonb NOT NULL DEFAULT '{}'::jsonb,
  ip              text,
  user_agent      text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_audit_actor   ON audit_events(actor_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_action  ON audit_events(action, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_entity  ON audit_events(entity_type, entity_id, created_at DESC);


CREATE TABLE IF NOT EXISTS quotations (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id            text    NOT NULL UNIQUE,
  status              text    NOT NULL DEFAULT 'draft',   -- draft | sent | accepted | expired

  -- Customer
  customer_name       text    NOT NULL,
  customer_mobile     text,
  customer_email      text,
  occasion            text,

  -- Product
  product_name        text,
  product_category    text,
  product_description text,
  product_image_path  text,

  -- Metal
  metal_type          text,
  metal_color         text,
  purity              text,
  gross_weight        double precision DEFAULT 0,
  net_weight          double precision DEFAULT 0,

  -- Diamond
  diamond_type        text,
  diamond_shape       text,
  diamond_carat       double precision DEFAULT 0,
  diamond_clarity     text,
  diamond_color       text,

  -- Gemstone
  gemstone            text,
  gemstone_carat      double precision DEFAULT 0,

  -- Certifications
  hallmark            text,
  certification       text,
  setting_style       text,

  -- Rates snapshot (frozen at creation)
  gold_rate_per_gram      double precision DEFAULT 0,
  diamond_rate_per_carat  double precision DEFAULT 0,
  gemstone_rate_per_carat double precision DEFAULT 0,

  -- Making
  making_charge_type      text DEFAULT 'per_gram',
  making_charge_value     double precision DEFAULT 0,

  -- Extras
  hallmark_charge         double precision DEFAULT 0,
  certification_charge    double precision DEFAULT 0,
  shipping_charge         double precision DEFAULT 0,

  -- Computed
  gold_cost           double precision DEFAULT 0,
  diamond_cost        double precision DEFAULT 0,
  gemstone_cost       double precision DEFAULT 0,
  making_charge       double precision DEFAULT 0,
  subtotal            double precision DEFAULT 0,
  gst_rate            double precision DEFAULT 0.03,
  gst_amount          double precision DEFAULT 0,
  final_price         double precision DEFAULT 0,

  -- Meta
  pricing_location    text,
  sales_executive     text,
  valid_till          date,
  notes               text,
  pdf_path            text,

  -- WhatsApp delivery
  whatsapp_status     text,
  whatsapp_message_id text,
  whatsapp_sent_at    timestamptz,
  whatsapp_error      text,

  -- Ownership (M2 — RBAC visibility scoping)
  owner_user_id       bigint REFERENCES users(id) ON DELETE SET NULL,

  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);
-- idx_quotations_owner is created in connection.js after the column migration
-- runs, so existing databases get the column added before the index references it.

CREATE INDEX IF NOT EXISTS idx_quotations_quote_id   ON quotations(quote_id);
CREATE INDEX IF NOT EXISTS idx_quotations_created_at ON quotations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_quotations_customer   ON quotations(customer_name);

-- ============================================================
-- Rate Master Tables
-- ============================================================

CREATE TABLE IF NOT EXISTS gold_rates (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location       text NOT NULL DEFAULT 'Mumbai',
  purity         text NOT NULL,
  rate_per_gram  double precision NOT NULL,
  source         text NOT NULL DEFAULT 'manual',
  is_override    boolean NOT NULL DEFAULT false,
  effective_date date NOT NULL DEFAULT current_date,
  updated_at     timestamptz NOT NULL DEFAULT now(),
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_gold_rates_loc_purity ON gold_rates(location, purity, updated_at DESC);

CREATE TABLE IF NOT EXISTS diamond_rates (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shape          text NOT NULL,
  clarity        text,
  color          text,
  rate_per_carat double precision NOT NULL,
  effective_date date NOT NULL DEFAULT current_date,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_diamond_rates_shape ON diamond_rates(shape, effective_date DESC);

CREATE TABLE IF NOT EXISTS gemstone_rates (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gemstone       text NOT NULL,
  grade          text,
  rate_per_carat double precision NOT NULL,
  effective_date date NOT NULL DEFAULT current_date,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_gemstone_rates_name ON gemstone_rates(gemstone, effective_date DESC);

CREATE TABLE IF NOT EXISTS making_charges (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category       text NOT NULL,
  charge_type    text NOT NULL,
  charge_value   double precision NOT NULL,
  effective_date date NOT NULL DEFAULT current_date,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_making_charges_cat ON making_charges(category, effective_date DESC);

-- ============================================================
-- M8 — Inventory + Procurement (ERP foundation)
--   These are brand-new tables fully defined here, so their inline indexes
--   are safe: CREATE TABLE IF NOT EXISTS runs fresh on already-deployed DBs
--   (the table doesn't exist yet) and creates the indexed columns atomically.
--   The deferred-index rule (see connection.js) only applies to indexes on
--   columns added via ALTER to pre-existing tables — e.g. quotations.inventory_item_id.
-- ============================================================

-- Vendors / suppliers.
CREATE TABLE IF NOT EXISTS suppliers (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_code      text NOT NULL UNIQUE,
  name               text NOT NULL,
  gst_number         text,
  contact_person     text,
  mobile             text,
  email              text,
  address            text,
  category           text,                  -- Gold | Diamond | Findings | Casting | Other
  notes              text,
  is_active          boolean NOT NULL DEFAULT true,
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_suppliers_active ON suppliers(is_active, name);

-- Stock items. Each row is a discrete piece (quantity defaults to 1 for unique
-- jewellery, but supports countable findings). Valuation is computed at read
-- time (net_weight x live gold rate + stone_value), never stored stale.
CREATE TABLE IF NOT EXISTS inventory_items (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku                   text NOT NULL UNIQUE,
  name                  text NOT NULL,
  category              text,
  metal_type            text,
  purity                text,
  gross_weight          double precision DEFAULT 0,
  net_weight            double precision DEFAULT 0,
  diamond_type          text,
  diamond_carat         double precision DEFAULT 0,
  gemstone              text,
  gemstone_carat        double precision DEFAULT 0,
  design_code           text,
  location              text NOT NULL DEFAULT 'Mumbai',
  status                text NOT NULL DEFAULT 'in_stock', -- in_stock | reserved | sold | repair | custom_order | archived
  quantity              integer NOT NULL DEFAULT 1,
  purchase_cost         numeric(14,2) DEFAULT 0,   -- total landed cost (from procurement)
  stone_value           numeric(14,2) DEFAULT 0,   -- diamond + gemstone value, added to market valuation
  making_cost           numeric(14,2) DEFAULT 0,
  image_url             text,
  certificate_url       text,
  supplier_id           bigint REFERENCES suppliers(id) ON DELETE SET NULL,
  purchase_id           bigint,                    -- loose link to procurement batch
  reserved_quotation_id text,                      -- quote_id currently holding the reservation
  sold_quotation_id     text,                      -- quote_id the item was sold against
  notes                 text,
  is_active             boolean NOT NULL DEFAULT true,
  created_by_user_id    bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_inventory_status   ON inventory_items(status, is_active);
CREATE INDEX IF NOT EXISTS idx_inventory_category ON inventory_items(category);
CREATE INDEX IF NOT EXISTS idx_inventory_sku      ON inventory_items(sku);
CREATE INDEX IF NOT EXISTS idx_inventory_supplier ON inventory_items(supplier_id);
CREATE INDEX IF NOT EXISTS idx_inventory_created  ON inventory_items(created_at DESC);

-- Append-only stock ledger. Stock status is never mutated without a paired
-- movement row (the audit_events log records the actor action separately).
CREATE TABLE IF NOT EXISTS inventory_movements (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inventory_item_id bigint NOT NULL REFERENCES inventory_items(id) ON DELETE CASCADE,
  direction         text NOT NULL,            -- in | out
  movement_type     text NOT NULL,            -- purchase|manufacture|return_in|transfer_in | sold|damaged|return_out|repair|transfer_out|quotation_reserve
  quantity          integer NOT NULL DEFAULT 1,
  weight            double precision DEFAULT 0,
  reason            text,
  ref_type          text,                     -- purchase | quotation | manual
  ref_id            text,
  actor_user_id     bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_inv_moves_item ON inventory_movements(inventory_item_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inv_moves_type ON inventory_movements(movement_type, created_at DESC);

-- Procurement batch header.
CREATE TABLE IF NOT EXISTS purchases (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_code      text NOT NULL UNIQUE,
  supplier_id        bigint REFERENCES suppliers(id) ON DELETE SET NULL,
  purchase_date      date NOT NULL DEFAULT current_date,
  invoice_number     text,
  total_amount       numeric(14,2) DEFAULT 0,
  notes              text,
  status             text NOT NULL DEFAULT 'recorded',  -- recorded | cancelled
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_purchases_supplier ON purchases(supplier_id, purchase_date DESC);
CREATE INDEX IF NOT EXISTS idx_purchases_date     ON purchases(purchase_date DESC);

-- Procurement line items. Each line spawns an inventory_items row (status
-- in_stock) + an inventory_movements row (direction in / type purchase).
CREATE TABLE IF NOT EXISTS purchase_items (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  purchase_id       bigint NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,
  inventory_item_id bigint REFERENCES inventory_items(id) ON DELETE SET NULL,
  name              text NOT NULL,
  category          text,
  metal_type        text,
  purity            text,
  gross_weight      double precision DEFAULT 0,
  net_weight        double precision DEFAULT 0,
  quantity          integer NOT NULL DEFAULT 1,
  unit_cost         numeric(14,2) DEFAULT 0,
  line_total        numeric(14,2) DEFAULT 0,
  notes             text,
  created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_purchase_items_po ON purchase_items(purchase_id);

-- ============================================================
-- M9 — Sales Orders + Production + Job Work + Repairs
--   All brand-new tables (no ALTER on existing tables), so inline indexes are
--   safe per the deferred-index rule in connection.js.
-- ============================================================

-- Confirmed customer orders, converted from a quotation.
CREATE TABLE IF NOT EXISTS sales_orders (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_code         text NOT NULL UNIQUE,
  quotation_id       bigint REFERENCES quotations(id) ON DELETE SET NULL,
  quote_code         text,                              -- snapshot of quotations.quote_id
  customer_id        bigint REFERENCES customers(id) ON DELETE SET NULL,
  customer_name      text,
  customer_mobile    text,
  product_name       text,
  product_category   text,
  total_amount       numeric(14,2) DEFAULT 0,
  advance_amount     numeric(14,2) DEFAULT 0,
  balance_amount     numeric(14,2) DEFAULT 0,
  status             text NOT NULL DEFAULT 'draft',     -- draft|confirmed|production|ready|delivered|cancelled
  expected_delivery  date,
  delivered_at       timestamptz,
  notes              text,
  owner_user_id      bigint REFERENCES users(id) ON DELETE SET NULL,
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_sales_orders_status   ON sales_orders(status);
CREATE INDEX IF NOT EXISTS idx_sales_orders_customer ON sales_orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_sales_orders_owner    ON sales_orders(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_sales_orders_quote    ON sales_orders(quotation_id);
CREATE INDEX IF NOT EXISTS idx_sales_orders_created  ON sales_orders(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sales_orders_delivery ON sales_orders(expected_delivery);

-- Karigars / job workers (labour). Distinct from suppliers (materials).
CREATE TABLE IF NOT EXISTS karigars (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  karigar_code       text NOT NULL UNIQUE,
  name               text NOT NULL,
  mobile             text,
  email              text,
  address            text,
  skill              text,                              -- setting | polishing | casting | general
  notes              text,
  is_active          boolean NOT NULL DEFAULT true,
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_karigars_active ON karigars(is_active, name);

-- Production jobs — one pipeline per sales order.
CREATE TABLE IF NOT EXISTS production_jobs (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_code             text NOT NULL UNIQUE,
  sales_order_id       bigint NOT NULL REFERENCES sales_orders(id) ON DELETE CASCADE,
  stage                text NOT NULL DEFAULT 'design_approved', -- design_approved|in_production|stone_setting|polishing|qc|ready|delivered
  assigned_employee_id bigint REFERENCES employees(id) ON DELETE SET NULL,
  karigar_id           bigint REFERENCES karigars(id) ON DELETE SET NULL,
  expected_date        date,
  completed_date       date,
  is_delayed           boolean NOT NULL DEFAULT false,
  notes                text,
  created_by_user_id   bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_production_so       ON production_jobs(sales_order_id);
CREATE INDEX IF NOT EXISTS idx_production_stage    ON production_jobs(stage);
CREATE INDEX IF NOT EXISTS idx_production_employee ON production_jobs(assigned_employee_id);

-- Production stage transition log (append-only).
CREATE TABLE IF NOT EXISTS production_events (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  production_job_id bigint NOT NULL REFERENCES production_jobs(id) ON DELETE CASCADE,
  stage             text NOT NULL,
  note              text,
  actor_user_id     bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_production_events_job ON production_events(production_job_id, created_at DESC);

-- Job work issued to a karigar (gold + labour accounting).
CREATE TABLE IF NOT EXISTS job_works (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_work_code      text NOT NULL UNIQUE,
  karigar_id         bigint REFERENCES karigars(id) ON DELETE SET NULL,
  sales_order_id     bigint REFERENCES sales_orders(id) ON DELETE SET NULL,
  inventory_item_id  bigint REFERENCES inventory_items(id) ON DELETE SET NULL,
  description        text,
  gold_issued_gm     double precision DEFAULT 0,
  gold_returned_gm   double precision DEFAULT 0,
  wastage_gm         double precision DEFAULT 0,
  labour_charge      numeric(14,2) DEFAULT 0,
  amount_paid        numeric(14,2) DEFAULT 0,
  payment_due        numeric(14,2) DEFAULT 0,
  status             text NOT NULL DEFAULT 'issued',    -- issued | in_progress | completed | cancelled
  issued_date        date NOT NULL DEFAULT current_date,
  completed_date     date,
  notes              text,
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_job_works_karigar ON job_works(karigar_id, status);
CREATE INDEX IF NOT EXISTS idx_job_works_status  ON job_works(status);
CREATE INDEX IF NOT EXISTS idx_job_works_so      ON job_works(sales_order_id);

-- Repair / service orders.
CREATE TABLE IF NOT EXISTS repair_orders (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repair_code        text NOT NULL UNIQUE,
  customer_id        bigint REFERENCES customers(id) ON DELETE SET NULL,
  customer_name      text,
  customer_mobile    text,
  item_description   text,
  issue_notes        text,
  received_date      date NOT NULL DEFAULT current_date,
  promised_date      date,
  charge             numeric(14,2) DEFAULT 0,
  status             text NOT NULL DEFAULT 'received',  -- received | in_progress | ready | delivered | cancelled
  delivered_at       timestamptz,
  notes              text,
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_repairs_status   ON repair_orders(status);
CREATE INDEX IF NOT EXISTS idx_repairs_customer ON repair_orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_repairs_received ON repair_orders(received_date DESC);

-- ============================================================
-- M10 — Finance + Accounts + Billing
--   All brand-new tables (no ALTER on existing tables) → inline indexes safe.
--   Double-entry capable: journal_entries (header) + journal_lines (DR/CR).
-- ============================================================

-- Chart-of-accounts top-level groups.
CREATE TABLE IF NOT EXISTS account_groups (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  nature      text NOT NULL,            -- asset | liability | income | expense | equity
  sort_order  integer NOT NULL DEFAULT 100,
  is_active   boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_account_groups_name ON account_groups(lower(name));

-- Ledger accounts (chart of accounts). `code` is the stable key the posting
-- engine resolves system accounts by (CASH, BANK, AR, AP, SALES, GST, …).
CREATE TABLE IF NOT EXISTS accounts (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code               text NOT NULL UNIQUE,
  name               text NOT NULL,
  group_id           bigint REFERENCES account_groups(id) ON DELETE SET NULL,
  nature             text NOT NULL,        -- denormalised from group for fast posting
  is_system          boolean NOT NULL DEFAULT false,  -- system accounts can't be deleted
  is_cash_bank       boolean NOT NULL DEFAULT false,  -- selectable as a payment account
  is_active          boolean NOT NULL DEFAULT true,
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_accounts_group ON accounts(group_id);
CREATE INDEX IF NOT EXISTS idx_accounts_active ON accounts(is_active, name);

-- Double-entry journal header.
CREATE TABLE IF NOT EXISTS journal_entries (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entry_code         text NOT NULL UNIQUE,            -- JE-YYYY-NNNN
  entry_date         date NOT NULL DEFAULT current_date,
  narration          text,
  source             text NOT NULL DEFAULT 'manual',  -- manual | payment | supplier_payment | expense | invoice
  ref_type           text,
  ref_id             text,
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_journal_date   ON journal_entries(entry_date DESC);
CREATE INDEX IF NOT EXISTS idx_journal_source ON journal_entries(source, created_at DESC);

-- Journal lines (each entry's debit/credit rows; service enforces DR = CR).
CREATE TABLE IF NOT EXISTS journal_lines (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  journal_entry_id  bigint NOT NULL REFERENCES journal_entries(id) ON DELETE CASCADE,
  account_id        bigint NOT NULL REFERENCES accounts(id) ON DELETE RESTRICT,
  debit             numeric(14,2) NOT NULL DEFAULT 0,
  credit            numeric(14,2) NOT NULL DEFAULT 0,
  created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_journal_lines_entry   ON journal_lines(journal_entry_id);
CREATE INDEX IF NOT EXISTS idx_journal_lines_account ON journal_lines(account_id, created_at DESC);

-- Payments — unified for customer receipts (in) and supplier payments (out).
CREATE TABLE IF NOT EXISTS payments (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_code       text NOT NULL UNIQUE,            -- PAY-YYYY-NNNN
  party_type         text NOT NULL,                   -- customer | supplier
  direction          text NOT NULL,                   -- in (receipt) | out (payment)
  sales_order_id     bigint REFERENCES sales_orders(id) ON DELETE SET NULL,
  purchase_id        bigint REFERENCES purchases(id) ON DELETE SET NULL,
  customer_id        bigint REFERENCES customers(id) ON DELETE SET NULL,
  supplier_id        bigint REFERENCES suppliers(id) ON DELETE SET NULL,
  amount             numeric(14,2) NOT NULL,
  mode               text NOT NULL DEFAULT 'cash',    -- cash | bank | upi | card | other
  account_id         bigint REFERENCES accounts(id) ON DELETE SET NULL, -- cash/bank account hit
  paid_at            date NOT NULL DEFAULT current_date,
  notes              text,
  journal_entry_id   bigint REFERENCES journal_entries(id) ON DELETE SET NULL,
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_payments_so       ON payments(sales_order_id);
CREATE INDEX IF NOT EXISTS idx_payments_purchase ON payments(purchase_id);
CREATE INDEX IF NOT EXISTS idx_payments_supplier ON payments(supplier_id);
CREATE INDEX IF NOT EXISTS idx_payments_party    ON payments(party_type, created_at DESC);

-- Expenses.
CREATE TABLE IF NOT EXISTS expenses (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expense_code       text NOT NULL UNIQUE,            -- EXP-YYYY-NNNN
  category           text NOT NULL,
  expense_account_id bigint REFERENCES accounts(id) ON DELETE SET NULL,
  amount             numeric(14,2) NOT NULL,
  expense_date       date NOT NULL DEFAULT current_date,
  mode               text NOT NULL DEFAULT 'cash',
  paid_account_id    bigint REFERENCES accounts(id) ON DELETE SET NULL,
  notes              text,
  receipt_url        text,
  journal_entry_id   bigint REFERENCES journal_entries(id) ON DELETE SET NULL,
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_expenses_date     ON expenses(expense_date DESC);
CREATE INDEX IF NOT EXISTS idx_expenses_category ON expenses(category);

-- Invoices / bills (distinct from quotations).
CREATE TABLE IF NOT EXISTS invoices (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_code       text NOT NULL UNIQUE,            -- INV-YYYY-NNNN
  sales_order_id     bigint REFERENCES sales_orders(id) ON DELETE SET NULL,
  quotation_id       bigint REFERENCES quotations(id) ON DELETE SET NULL,
  customer_id        bigint REFERENCES customers(id) ON DELETE SET NULL,
  customer_name      text,
  customer_mobile    text,
  product_name       text,
  product_category   text,
  metal_value        numeric(14,2) DEFAULT 0,
  making_charge      numeric(14,2) DEFAULT 0,
  stone_value        numeric(14,2) DEFAULT 0,
  subtotal           numeric(14,2) DEFAULT 0,
  tax_rate           numeric(6,2)  DEFAULT 3,         -- GST % placeholder
  tax_amount         numeric(14,2) DEFAULT 0,
  total_amount       numeric(14,2) DEFAULT 0,
  paid_amount        numeric(14,2) DEFAULT 0,
  balance_amount     numeric(14,2) DEFAULT 0,
  status             text NOT NULL DEFAULT 'issued',  -- issued | partial | paid | cancelled
  notes              text,
  journal_entry_id   bigint REFERENCES journal_entries(id) ON DELETE SET NULL,
  created_by_user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_invoices_so       ON invoices(sales_order_id);
CREATE INDEX IF NOT EXISTS idx_invoices_customer ON invoices(customer_id);
CREATE INDEX IF NOT EXISTS idx_invoices_status   ON invoices(status);
CREATE INDEX IF NOT EXISTS idx_invoices_created  ON invoices(created_at DESC);
