-- ============================================================
-- JBOS PostgreSQL Schema (Neon)
-- Idempotent (CREATE … IF NOT EXISTS). Bootstrap-safe on every boot.
-- ============================================================

CREATE TABLE IF NOT EXISTS quotations (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id            text    NOT NULL UNIQUE,
  status              text    NOT NULL DEFAULT 'draft',   -- draft | sent | accepted | expired

  -- Customer
  customer_name       text    NOT NULL,
  customer_mobile     text,
  customer_email      text,
  occasion            text,

  -- Product
  product_name        text,
  product_category    text,
  product_description text,
  product_image_path  text,

  -- Metal
  metal_type          text,
  metal_color         text,
  purity              text,
  gross_weight        double precision DEFAULT 0,
  net_weight          double precision DEFAULT 0,

  -- Diamond
  diamond_type        text,
  diamond_shape       text,
  diamond_carat       double precision DEFAULT 0,
  diamond_clarity     text,
  diamond_color       text,

  -- Gemstone
  gemstone            text,
  gemstone_carat      double precision DEFAULT 0,

  -- Certifications
  hallmark            text,
  certification       text,
  setting_style       text,

  -- Rates snapshot (frozen at creation)
  gold_rate_per_gram      double precision DEFAULT 0,
  diamond_rate_per_carat  double precision DEFAULT 0,
  gemstone_rate_per_carat double precision DEFAULT 0,

  -- Making
  making_charge_type      text DEFAULT 'per_gram',
  making_charge_value     double precision DEFAULT 0,

  -- Extras
  hallmark_charge         double precision DEFAULT 0,
  certification_charge    double precision DEFAULT 0,
  shipping_charge         double precision DEFAULT 0,

  -- Computed
  gold_cost           double precision DEFAULT 0,
  diamond_cost        double precision DEFAULT 0,
  gemstone_cost       double precision DEFAULT 0,
  making_charge       double precision DEFAULT 0,
  subtotal            double precision DEFAULT 0,
  gst_rate            double precision DEFAULT 0.03,
  gst_amount          double precision DEFAULT 0,
  final_price         double precision DEFAULT 0,

  -- Meta
  pricing_location    text,
  sales_executive     text,
  valid_till          date,
  notes               text,
  pdf_path            text,

  -- WhatsApp delivery
  whatsapp_status     text,
  whatsapp_message_id text,
  whatsapp_sent_at    timestamptz,
  whatsapp_error      text,

  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_quotations_quote_id   ON quotations(quote_id);
CREATE INDEX IF NOT EXISTS idx_quotations_created_at ON quotations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_quotations_customer   ON quotations(customer_name);

-- ============================================================
-- Rate Master Tables
-- ============================================================

CREATE TABLE IF NOT EXISTS gold_rates (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location       text NOT NULL DEFAULT 'Mumbai',
  purity         text NOT NULL,
  rate_per_gram  double precision NOT NULL,
  source         text NOT NULL DEFAULT 'manual',
  is_override    boolean NOT NULL DEFAULT false,
  effective_date date NOT NULL DEFAULT current_date,
  updated_at     timestamptz NOT NULL DEFAULT now(),
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_gold_rates_loc_purity ON gold_rates(location, purity, updated_at DESC);

CREATE TABLE IF NOT EXISTS diamond_rates (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shape          text NOT NULL,
  clarity        text,
  color          text,
  rate_per_carat double precision NOT NULL,
  effective_date date NOT NULL DEFAULT current_date,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_diamond_rates_shape ON diamond_rates(shape, effective_date DESC);

CREATE TABLE IF NOT EXISTS gemstone_rates (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gemstone       text NOT NULL,
  grade          text,
  rate_per_carat double precision NOT NULL,
  effective_date date NOT NULL DEFAULT current_date,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_gemstone_rates_name ON gemstone_rates(gemstone, effective_date DESC);

CREATE TABLE IF NOT EXISTS making_charges (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category       text NOT NULL,
  charge_type    text NOT NULL,
  charge_value   double precision NOT NULL,
  effective_date date NOT NULL DEFAULT current_date,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_making_charges_cat ON making_charges(category, effective_date DESC);
